### ISSUE TITLE
Model forward error when exec first GraphConv (MatMul)

### ISSUE THREAD

**Issue by HUGHNew** [kimmo1019/DeepCDR#2]
Thanks for your good work. I have encountered an unexpected problem when running the code. As running `run_DeepCDR.py`, an InternalError would occur when doing the matmul op in the first `GraphConv`.
Do you have any idea about it? The details are listed as follow.

---

```python
# predict.py
# the above is same as run_DeepCDR.py
def main():
    random.seed(0)
    mutation_feature, drug_feature,gexpr_feature,methylation_feature, data_idx = MetadataGenerate(Drug_info_file,Cell_line_info_file,Genomic_mutation_file,Drug_feature_file,Gene_expression_file,Methylation_file,False)
    data_train_idx,data_test_idx = DataSplit(data_idx)
    data_test_idx = data_test_idx[:2]
    #Extract features for training and test
    X_drug_data_test,X_mutation_data_test,X_gexpr_data_test,X_methylation_data_test,Y_test,cancer_type_test_list = FeatureExtract(data_test_idx,drug_feature,mutation_feature,gexpr_feature,methylation_feature)
    X_drug_feat_data_test = [item[0] for item in X_drug_data_test]
    X_drug_feat_data_test = np.array(X_drug_feat_data_test)#nb_instance * Max_stom * feat_dim
    X_drug_adj_data_test = [item[1] for item in X_drug_data_test]
    X_drug_adj_data_test = np.array(X_drug_adj_data_test)#nb_instance * Max_stom * Max_stom  

    drug_dim = X_drug_data_test[0][0].shape[-1]
    print(X_drug_data_test[0][0].shape)
    mutation_dim = X_mutation_data_test.shape[-2]
    gexpr_dim = X_gexpr_data_test.shape[-1]
    methy_dim = X_methylation_data_test.shape[-1]
    model = KerasMultiSourceGCNModel(use_mut,use_gexp,use_methy).createMaster(drug_dim,mutation_dim,gexpr_dim,methy_dim,args.unit_list,args.use_relu,args.use_bn,args.use_GMP)
    ModelEvaluate(model,X_drug_data_test,X_mutation_data_test,X_gexpr_data_test,X_methylation_data_test,Y_test,cancer_type_test_list,'%s/DeepCDR_%s.log'%(DPATH,model_suffix))
```

Traceback (most recent call last):
  File "predict.py", line 222, in <module>
    main()
  File "predict.py", line 219, in main
    ModelEvaluate(model,X_drug_data_test,X_mutation_data_test,X_gexpr_data_test,X_methylation_data_test,Y_test,cancer_type_test_list,'%s/DeepCDR_%s.log'%(DPATH,model_suffix))
  File "predict.py", line 194, in ModelEvaluate
    Y_pred = model.predict([X_drug_feat_data_test,X_drug_adj_data_test,X_mutation_data_test,X_gexpr_data_test,X_methylation_data_test])
  File "/micromamba/envs/cdr/lib/python3.7/site-packages/keras/engine/training.py", line 1842, in predict
    verbose=verbose, steps=steps)
  File "/micromamba/envs/cdr/lib/python3.7/site-packages/keras/engine/training.py", line 1337, in _predict_loop
    batch_outs = f(ins_batch)
  File "/micromamba/envs/cdr/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2475, in __call__
    **self.session_kwargs)
  File "/micromamba/envs/cdr/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/micromamba/envs/cdr/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/micromamba/envs/cdr/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/micromamba/envs/cdr/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed : a.shape=(100, 75), b.shape=(75, 256), m=100, n=256, k=75
         [[node graph_conv_1/MatMul (defined at /micromamba/envs/cdr/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:1067) ]]
         [[node output/BiasAdd (defined at /micromamba/envs/cdr/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3781) ]]

Caused by op 'graph_conv_1/MatMul', defined at:
  File "predict.py", line 222, in <module>
    main()
  File "predict.py", line 218, in main
    model = KerasMultiSourceGCNModel(use_mut,use_gexp,use_methy).createMaster(drug_dim,mutation_dim,gexpr_dim,methy_dim,args.unit_list,args.use_relu,args.use_bn,args.use_GMP)
  File "/space/CBDD/DeepCDR/prog/model.py", line 31, in createMaster
    GCN_layer = GraphConv(units=units_list[0],step_num=1)([drug_feat_input,drug_adj_input])
  File "/micromamba/envs/cdr/lib/python3.7/site-packages/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)
  File "/space/CBDD/DeepCDR/prog/layers/graph.py", line 57, in call
    outputs = self.activation(self._call(features, edges))
  File "/space/CBDD/DeepCDR/prog/layers/graph.py", line 145, in _call
    features = K.dot(features, self.W)
  File "/micromamba/envs/cdr/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 1067, in dot
    return tf.reshape(tf.matmul(xt, yt),
  File "/micromamba/envs/cdr/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 2455, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/micromamba/envs/cdr/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5333, in mat_mul
    name=name)
  File "/micromamba/envs/cdr/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/micromamba/envs/cdr/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/micromamba/envs/cdr/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/micromamba/envs/cdr/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): Blas GEMM launch failed : a.shape=(100, 75), b.shape=(75, 256), m=100, n=256, k=75
         [[node graph_conv_1/MatMul (defined at /micromamba/envs/cdr/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:1067) ]]
         [[node output/BiasAdd (defined at /micromamba/envs/cdr/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3781) ]]

```python
# env
python==3.7.12
tensorflow-gpu==1.13.1
keras==2.1.4
hickle>=2.1.0
pandas<1.4
scikit-learn==0.21.3
cudnn=7.3.1
cudatoolkit=10.0
```

**Comment by vinay-swamy** [comment]
I ran into the same issue @HUGHNew  did you solve it?

**Comment by HUGHNew** [comment]
> I ran into the same issue [@HUGHNew](https://github.com/HUGHNew) did you solve it?

Update `keras` to 3.x and use `PyTorch 2.x` as keras backend framework (get rid of `tensorflow`). (see [here](https://github.com/HUGHNew/DeepCDR-keras3/blob/torch/requirements-keras3.txt))
Then some minor modifications will make it runable.
Or you can take a look at [My repo](https://github.com/HUGHNew/DeepCDR-keras3)
